# Generated by Django 4.2.6 on 2023-10-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('guest_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=20)),
                ('addr_id', models.CharField(max_length=10)),
                ('guest_tel', models.CharField(max_length=11)),
                ('guest_pwd', models.CharField(max_length=16)),
            ],
        ),
    ]
