# Generated by Django 4.2.6 on 2023-10-31 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='guest',
        ),
    ]
