# Generated by Django 4.2.6 on 2023-10-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testapp', '0002_delete_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addr',
            fields=[
                ('addr_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'addr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('canteen_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('canteen_name', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'canteen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CanteenManager',
            fields=[
                ('manager_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=5)),
                ('manager_tel', models.CharField(max_length=11)),
                ('canteen_id', models.CharField(max_length=2)),
                ('manager_pwd', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'canteen_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=16)),
                ('dish_price', models.IntegerField()),
                ('dish_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dish',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=20)),
                ('guest_tel', models.CharField(max_length=11)),
                ('guest_pwd', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'guest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_dish_num', models.IntegerField()),
                ('order_time', models.CharField(max_length=20)),
                ('order_amount', models.IntegerField()),
                ('order_status', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('guest_id', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=10)),
                ('seller_pwd', models.CharField(max_length=16)),
                ('seller_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'seller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhatToEat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canteen_name', models.CharField(max_length=5)),
                ('seller_name', models.CharField(max_length=10)),
                ('seller_description', models.CharField(blank=True, max_length=100, null=True)),
                ('dish_name', models.CharField(max_length=16)),
                ('dish_price', models.IntegerField()),
                ('dish_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'what_to_eat',
                'managed': False,
            },
        ),
    ]
